{
	"default":{
		"basePath":"modules/",
		"modules":{
			"tangram2":{
				"js":["tangram2/tangram-compatible.js","tangram2/tangram-shim.js"]
			},
			"tangram-baseUI":{
				"js":["tangram-baseUI/tangram-baseUI.js"],
				"dependencies":["tangram2"]
			},
			"bootstrap":{
				"less":["bootstrap/bootstrap-debug.less"],
				"css":["bootstrap/bootstrap-debug.css"],
				"dependencies":[]
			},
			"less":{
				"js":["less/less.js"]
			},
			"nuit-common":{
				"js":["nuit-common/nuit.js"],
				"less":["nuit-common/nuit.common.less"],
				"css":["nuit-common/nuit.common.css"],
				"dependencies":["bootstrap"]
			},
			"nuit-ajax":{
				"js":["nuit-ajax/nuit.ajax.js"],
				"dependencies":["tangram2","nuit-common","nuit-dialog"]
			},
			"nuit-dialog":{
				"js":["nuit-dialog/tangramUI-dialog.js","nuit-dialog/nuit.dialog.js"],
				"less":["nuit-dialog/nuit.dialog.less"],
				"css":["nuit-dialog/nuit.dialog.css"],
				"dependencies":["tangram2","tangram-baseUI","nuit-common"]
			},
			"nuit-buttonmenu":{
				"js":["nuit-buttonmenu/nuit.buttonmenu.js"],
				"less":["nuit-buttonmenu/nuit.buttonmenu.less"],
				"css":["nuit-buttonmenu/nuit.buttonmenu.css"],
				"dependencies":["tangram2","tangram-baseUI","nuit-common"]
			},
			"nuit-combox":{
				"js":["nuit-combox/nuit.combox.js"],
				"less":["nuit-combox/nuit.combox.less"],
				"css":["nuit-combox/nuit.combox.css"],
				"dependencies":["tangram2","tangram-baseUI","nuit-common"]
			},
			"nuit-form":{
				"less":["nuit-form/nuit.form.less"],
				"dependencies":["bootstrap","nuit-common"]
			},
			"nuit-grid":{
				"js":["nuit-grid/js/tangram.grid.js","nuit-grid/js/tangram.grid.keyboard.js","nuit-grid/js/tangram.grid.columndragsort.js","nuit-grid/js/tangram.grid.columnfreeze.js","nuit-grid/js/tangram.grid.editable.js","nuit-grid/js/tangram.grid.groupsummary.js","nuit-grid/js/tangram.grid.pagesort.js","nuit-grid/js/tangram.grid.rowexpand.js","nuit-grid/js/tangram.grid.treegrid.js","nuit-grid/js/tangram.grid.rowsortable.js","nuit-grid/js/nuit.grid.js"],
				"less":["nuit-grid/nuit.grid.less"],
				"css":["nuit-grid/nuit.grid.css"],
				"dependencies":["tangram2","tangram-baseUI","nuit-common"]
			},
			"nuit-pager":{
				"js":["nuit-pager/nuit.pager.js"],
				"less":["nuit-pager/nuit.pager.less"],
				"css":["nuit-pager/nuit.pager.css"],
				"dependencies":["tangram2","tangram-baseUI","nuit-form"]
			},
			"nuit-tree":{
				"js":["nuit-tree/tangram.tree.js","nuit-tree/tangram.tree.checkbox.js","nuit-tree/nuit.tree.js"],
				"css":["nuit-tree/nuit.tree.less"],
				"less":["nuit-tree/nuit.tree.less"],
				"dependencies":["tangram2","tangram-baseUI","nuit-common"]
			},
			"nuit-servicetree":{
				"js":["nuit-servicetree/nuit.servicetree.js"],
				"dependencies":["tangram2","tangram-baseUI","nuit-common","nuit-dialog","nuit-tree"]
			},
			"nuit-suggestion":{
				"js":["nuit-suggestion/tangramUI-suggestion.js","nuit-suggestion/nuit.suggestion.js"],
				"less":["nuit-suggestion/nuit.suggestion.less"],
				"css":["nuit-suggestion/nuit.suggestion.css"],
				"dependencies":["tangram2","tangram-baseUI","nuit-common"]
			},
			"nuit-tab":{
				"js":["nuit-tab/nuit.tab.js"],
				"less":["nuit-tab/nuit.tab.less"],
				"css":["nuit-tab/nuit.tab.css"],
				"dependencies":["tangram2","tangram-baseUI","nuit-common"]
			},
			"nuit-tooltip":{
				"js":["nuit-tooltip/tangramUI-tooltip.js","nuit-tooltip/nuit.tooltip.js"],
				"less":["nuit-tooltip/nuit.tooltip.less"],
				"css":["nuit-tooltip/nuit.tooltip.css"],
				"dependencies":["tangram2","tangram-baseUI","nuit-common"]
			},
			"nuit-validate":{
				"js":["nuit-validate/nuit.validate.js"],
				"dependencies":["tangram2","tangram-baseUI","nuit-form"]
			},
			"nuit-persist":{
				"js":["nuit-persist/nuit.persist.js"],
				"dependencies":["nuit-common"]
			},
			"nuit-versiontip":{
				"js":["nuit-versiontip/nuit.versiontip.js"],
				"less":["nuit-versiontip/nuit.versiontip.less"],
				"css":["nuit-versiontip/nuit.versiontip.css"],
				"dependencies":["tangram2","tangram-baseUI","nuit-persist","nuit-form"]
			},
			"nuit-wizard":{
				"js":["nuit-wizard/nuit.wizard.js"],
				"css":["nuit-wizard/nuit.wizard.less"],
				"less":["nuit-wizard/nuit.wizard.less"],
				"dependencies":["tangram2","tangram-baseUI","nuit-common"]
			}
		}
	}
}
