{
	"default":{
		"basePath":"modules/",
		"modules":{
			"base":{
				"js":["base/base.js","base/common.js"],
				"css":["base/reset.css"],
				"less":["base/reset.less"]
			 },
			 "pageA":{
				 "js":["pageA/pageA-util.js","pageA/pageA.js"],
				 "css":["pageA/pageA.css"],
				 "dependencies":["base"]
			 }
		}
	}
}